### ISSUE TITLE
ERROR: Path "/local.js" already exist.

### ISSUE THREAD

**Issue by briansanchez** [maciejtreder/ng-toolkit#402] opened 2018-08-03 18:46 UTC
## I'm submitting a...

<pre>

<code>
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[ X] @ng-toolkit/universal
</code></pre>

## Current behavior

ran this ng add @ng-toolkit/universal

## Expected behavior

this behavior 
https://youtu.be/hxG9nuvnh-A?t=7m58s

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by maciejtreder** [comment] 2018-08-06 13:43
Duplicate of #395

**Closed by maciejtreder** 2018-08-06 13:43 UTC
