### ISSUE TITLE
Path "/local.js" already exist.

### ISSUE THREAD

**Issue by sanfelici** [maciejtreder/ng-toolkit#395] opened 2018-07-28 15:51 UTC
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[ ] @ng-toolkit/universal
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by sanfelici** [comment] 2018-07-28 15:54
in fase di installazione 
ng add @ng-toolkit/universal
mi da: Path "/local.js" already exist.

**Comment by Glangouet** [comment] 2018-07-28 17:06
up

**Comment by sanfelici** [comment] 2018-07-28 17:11
?

**Comment by Glangouet** [comment] 2018-07-30 08:06
fix problem, change your develop angular cli version to 6.0.7 and it works.

**Comment by sanfelici** [comment] 2018-07-30 10:56
Ok,grazie, proverò

**Comment by Xesenix** [comment] 2018-07-30 11:54
This is duplicate of https://github.com/maciejtreder/ng-toolkit/issues/390
@Glangouet that resolves the problem partially for me but still after building and trying to run server I get:

```
Error: Cannot find module './dist/server'
```
That's on a basic project created with `ng create new name --routing --style=sass` and `ng add @ng-toolkit/universal`

**Comment by maciejtreder** [comment] 2018-07-30 15:01
I will just keep it here, as a note: https://github.com/angular/devkit/issues/745

**Comment by MdShuaib** [comment] 2018-07-31 07:30
> if you are using angular-cli: 6.1.1

> Downgrade to lower version of angular-cli

`npm uninstall -g @angular/cli `
`npm cache verify`
`npm install -g @angular/cli@6.0.8`
`ng add @ng-toolkit/universal`

> And it works for me!

**Comment by maciejtreder** [comment] 2018-08-09 11:58
In the recent release (1.1.41) I added a workaround for this issue.

**Closed by maciejtreder** 2018-08-09 11:58 UTC
