### ISSUE TITLE
Getting error while running npm run server 

### ISSUE THREAD

**Issue by ASHISH060792** [maciejtreder/ng-toolkit#356] opened 2018-07-02 10:58 UTC
ReferenceError: localStorage is not defined

**Comment by chrisleekr** [comment] 2018-07-04 13:06
I am getting this error too. 

There will be a fix soon? @maciejtreder

**Comment by maciejtreder** [comment] 2018-07-04 13:07
Ill do my best to take a look at it today/tomorrow in the evening :)

**Comment by chrisleekr** [comment] 2018-07-04 13:07
@maciejtreder That is amazing. Thanks. :)

**Comment by RitaRibeiroHub** [comment] 2018-07-04 15:23
Hi! I'm getting this error when i running npm run server:
server.app.listen(port, () => {
           ^

TypeError: Cannot read property 'listen' of undefined
    at Object.<anonymous> (C:\work\Lat\app-lat\LAT\local.js:6:12)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:190:16)
    at bootstrap_node.js:662:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-app@0.0.0 server: `node local.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-app@0.0.0 server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by ZhipengZeng** [comment] 2018-07-06 03:29
Hi,

I have upgraded from ng5 to ng6, everything is fine.
I ran `ng build --prod` then
I encountered this error below when I ran `npm run server`.
It seems the server didn't get generated by `ng build --prod`

any ideas?

Thanks in advance
=====================
$ npm run server

> myapp@0.0.0 server <location>\sou
> node local.js

module.js:538
    throw err;
    ^

Error: Cannot find module './dist/server'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (<location>\sou\local.js:4:16)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myapp@0.0.0 server: `node local.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the soucanada@0.0.0 server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     <mycomputer>\AppData\Roaming\npm-cache\_logs\2018-07-06T03_22_46_792Z-debug.log

**Comment by ZhipengZeng** [comment] 2018-07-06 03:45
I figured it out. 
I should have used `npm run build:prod`

**Comment by maciejtreder** [comment] 2018-07-06 07:17
@RitaRibeiroHub @chrisleekr @ASHISH060792 

This issue is fixed with the latest build. Please verify :)

**Closed by maciejtreder** 2018-07-06 07:17 UTC
Labels: comp: universal, p2, status: open, type: enhancement

**Comment by ASHISH060792** [comment] 2018-07-09 09:32
Issue has been fixed but now i am getting below error.

ERROR TypeError: o is not a constructor
    at o (G:\Projects\Angular_Projects\Live_Projects\Git\dg_v6\dist\server.js:179433:7016)
    at Object.z [as init] (G:\Projects\Angular_Projects\Live_Projects\Git\dg_v6\dist\server.js:179433:2204)
    at AppComponent.module.exports../src/app/app.component.ts.AppComponent.ngOnInit (G:\Projects\Angular_Projects\Live_Projects\Git\dg_v6\dist\server.js:190805:13)
    at checkAndUpdateDirectiveInline (G:\Projects\Angular_Projects\Live_Projects\Git\dg_v6\dist\server.js:9490:19)
    at checkAndUpdateNodeInline (G:\Projects\Angular_Projects\Live_Projects\Git\dg_v6\dist\server.js:10754:20)
    at checkAndUpdateNode (G:\Projects\Angular_Projects\Live_Projects\Git\dg_v6\dist\server.js:10716:16)
    at prodCheckAndUpdateNode (G:\Projects\Angular_Projects\Live_Projects\Git\dg_v6\dist\server.js:11256:5)
    at Object.updateDirectives (G:\Projects\Angular_Projects\Live_Projects\Git\dg_v6\dist\server.js:190671:401)
    at Object.updateDirectives (G:\Projects\Angular_Projects\Live_Projects\Git\dg_v6\dist\server.js:11045:72)
    at Object.checkAndUpdateView (G:\Projects\Angular_Projects\Live_Projects\Git\dg_v6\dist\server.js:10698:14)
ERROR TypeError: this._results[getSymbolIterator(...)] is not a function
    at QueryList.module.exports.QueryList.(anonymous function) [as null] (G:\Projects\Angular_Projects\Live_Projects\Git\dg_v6\dist\server.js:5302:103)
    at iterateListLike (G:\Projects\Angular_Projects\Live_Projects\Git\dg_v6\dist\server.js:5845:48)
    at DefaultIterableDiffer.module.exports.DefaultIterableDiffer.check (G:\Projects\Angular_Projects\Live_Projects\Git\dg_v6\dist\server.js:6027:13)
    at DefaultIterableDiffer.module.exports.DefaultIterableDiffer.diff (G:\Projects\Angular_Projects\Live_Projects\Git\dg_v6\dist\server.js:5989:18)
    at NgForOf.module.exports.NgForOf.ngDoCheck (G:\Projects\Angular_Projects\Live_Projects\Git\dg_v6\dist\server.js:53122:40)
    at checkAndUpdateDirectiveInline (G:\Projects\Angular_Projects\Live_Projects\Git\dg_v6\dist\server.js:9493:19)
    at checkAndUpdateNodeInline (G:\Projects\Angular_Projects\Live_Projects\Git\dg_v6\dist\server.js:10754:20)
    at checkAndUpdateNode (G:\Projects\Angular_Projects\Live_Projects\Git\dg_v6\dist\server.js:10716:16)
    at prodCheckAndUpdateNode (G:\Projects\Angular_Projects\Live_Projects\Git\dg_v6\dist\server.js:11256:5)
    at Object.View_NgbTabset_0.i0.ɵvid._co [as updateDirectives] (G:\Projects\Angular_Projects\Live_Projects\Git\dg_v6\dist\server.js:188647:751)
ERROR TypeError: this._results[getSymbolIterator(...)] is not a function
    at QueryList.module.exports.QueryList.(anonymous function) [as null] (G:\Projects\Angular_Projects\Live_Projects\Git\dg_v6\dist\server.js:5302:103)
    at iterateListLike (G:\Projects\Angular_Projects\Live_Projects\Git\dg_v6\dist\server.js:5845:48)
    at DefaultIterableDiffer.module.exports.DefaultIterableDiffer.check (G:\Projects\Angular_Projects\Live_Projects\Git\dg_v6\dist\server.js:6027:13)
    at DefaultIterableDiffer.module.exports.DefaultIterableDiffer.diff (G:\Projects\Angular_Projects\Live_Projects\Git\dg_v6\dist\server.js:5989:18)
    at NgForOf.module.exports.NgForOf.ngDoCheck (G:\Projects\Angular_Projects\Live_Projects\Git\dg_v6\dist\server.js:53122:40)
    at checkAndUpdateDirectiveInline (G:\Projects\Angular_Projects\Live_Projects\Git\dg_v6\dist\server.js:9493:19)
    at checkAndUpdateNodeInline (G:\Projects\Angular_Projects\Live_Projects\Git\dg_v6\dist\server.js:10754:20)
    at checkAndUpdateNode (G:\Projects\Angular_Projects\Live_Projects\Git\dg_v6\dist\server.js:10716:16)
    at prodCheckAndUpdateNode (G:\Projects\Angular_Projects\Live_Projects\Git\dg_v6\dist\server.js:11256:5)
    at Object.View_NgbTabset_0.i0.ɵvid._co [as updateDirectives] (G:\Projects\Angular_Projects\Live_Projects\Git\dg_v6\dist\server.js:188647:751)
ERROR TypeError: this._results[getSymbolIterator(...)] is not a function
    at QueryList.module.exports.QueryList.(anonymous function) [as null] (G:\Projects\Angular_Projects\Live_Projects\Git\dg_v6\dist\server.js:5302:103)
    at iterateListLike (G:\Projects\Angular_Projects\Live_Projects\Git\dg_v6\dist\server.js:5845:48)
    at DefaultIterableDiffer.module.exports.DefaultIterableDiffer.check (G:\Projects\Angular_Projects\Live_Projects\Git\dg_v6\dist\server.js:6027:13)
    at DefaultIterableDiffer.module.exports.DefaultIterableDiffer.diff (G:\Projects\Angular_Projects\Live_Projects\Git\dg_v6\dist\server.js:5989:18)
    at NgForOf.module.exports.NgForOf.ngDoCheck (G:\Projects\Angular_Projects\Live_Projects\Git\dg_v6\dist\server.js:53122:40)
    at checkAndUpdateDirectiveInline (G:\Projects\Angular_Projects\Live_Projects\Git\dg_v6\dist\server.js:9493:19)
    at checkAndUpdateNodeInline (G:\Projects\Angular_Projects\Live_Projects\Git\dg_v6\dist\server.js:10754:20)
    at checkAndUpdateNode (G:\Projects\Angular_Projects\Live_Projects\Git\dg_v6\dist\server.js:10716:16)
    at prodCheckAndUpdateNode (G:\Projects\Angular_Projects\Live_Projects\Git\dg_v6\dist\server.js:11256:5)
    at Object.View_NgbTabset_0.i0.ɵvid._co [as updateDirectives] (G:\Projects\Angular_Projects\Live_Projects\Git\dg_v6\dist\server.js:188647:751)
ERROR TypeError: window.gtag is not a function
    at SafeSubscriber._next (G:\Projects\Angular_Projects\Live_Projects\Git\dg_v6\dist\server.js:190795:28)
    at SafeSubscriber.module.exports.SafeSubscriber.__tryOrUnsub (G:\Projects\Angular_Projects\Live_Projects\Git\dg_v6\dist\server.js:58307:16)
    at SafeSubscriber.module.exports.SafeSubscriber.next (G:\Projects\Angular_Projects\Live_Projects\Git\dg_v6\dist\server.js:58245:22)
    at Subscriber.module.exports.Subscriber._next (G:\Projects\Angular_Projects\Live_Projects\Git\dg_v6\dist\server.js:58189:26)
    at Subscriber.module.exports.Subscriber.next (G:\Projects\Angular_Projects\Live_Projects\Git\dg_v6\dist\server.js:58166:18)
    at Subject.module.exports.Subject.next (G:\Projects\Angular_Projects\Live_Projects\Git\dg_v6\dist\server.js:59310:25)
    at G:\Projects\Angular_Projects\Live_Projects\Git\dg_v6\dist\server.js:83208:22
    at ZoneDelegate.module.exports.ZoneDelegate.invoke (G:\Projects\Angular_Projects\Live_Projects\Git\dg_v6\dist\server.js:254107:26)
    at Object.onInvoke (G:\Projects\Angular_Projects\Live_Projects\Git\dg_v6\dist\server.js:4216:33)
    at ZoneDelegate.module.exports.ZoneDelegate.invoke (G:\Projects\Angular_Projects\Live_Projects\Git\dg_v6\dist\server.js:254106:32)

**Comment by maciejtreder** [comment] 2018-07-09 09:39
@ASHISH060792 Could you give me an access to your project code? GitHub? GitLab? BitBucket? Any other hosting?

**Comment by ASHISH060792** [comment] 2018-07-09 09:41
Sorry, it's an internal project I can't give you access.

**Comment by maciejtreder** [comment] 2018-07-09 09:42
Sad to hear that. I am unable to reproduce your issue then :(

**Comment by ASHISH060792** [comment] 2018-07-17 06:50
Is the express secure for a cloud-based application

**Comment by ASHISH060792** [comment] 2018-07-18 08:53
why there are two assets folder on in dist and another one in dist/browser folder?
