### ISSUE TITLE
Zone already loaded on npm run server

### ISSUE THREAD

**Issue by dosapati** [maciejtreder/ng-toolkit#478] opened 2018-10-14 22:16 UTC
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[x] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior
Started using ng-toolkit, it generated all the sources and code is build successfully. When I run the "npm run server" getting error as "Zone already loaded". I found out I have zone imports in polyfills.ts and server.ts. Need help in resolve the issue?

Error: Zone already loaded.
    at sample-app/dist/server.js:200473:15
    at sample-app/dist/server.js:201085:3
    at module.exports.FUNCTION (sample-app/dist/server.js:200451:10)
    at Object.module.exports.Object.defineProperty.value (sample-app/dist/server.js:200453:2)
    at __webpack_require__ (sample-app/dist/server.js:21:30)
    at Object.zone.js/dist/zone (sample-app/dist/server.js:242055:18)
    at __webpack_require__ (sample-app/dist/server.js:226904:30)
    at Object../src/polyfills.ts (sample-app/dist/server.js:240817:1)
    at __webpack_require__ (sample-app/dist/server.js:226904:30)
    at Object../src/app/app.module.ts (sample-app/dist/server.js:229925:1)

## Expected behavior
should run the 

## Minimal reproduction of the problem with instructions
* Generate a Angular project with polyfills.ts which has import 'zone.js/dist/zone';
* use ng add @ng-toolkit/universal
* build using npm run build:prod
* run using npm run server

<pre><code>
Angular version: 6.1.2

- Node version: v8.11.3  
- Platform:  Mac

**Comment by amalshehu** [comment] 2018-11-24 11:11
Have the same issue, @dosapati Made it working?

**Comment by dosapati** [comment] 2018-11-24 12:11
Nope. I couldn’t solve it

**Comment by amalshehu** [comment] 2018-12-06 15:49
Planning to move forward with other options.

**Comment by KingDarBoja** [comment] 2019-12-30 13:53
Closing now as there have been new releases and the issue is already too old.

Please open a new issue if you find this same bug.

Cheers!

**Closed by KingDarBoja** 2019-12-30 13:53 UTC
